OSStartHighRdy
	LDR R0, =NVIC_SYSPRI14
	LDR R1, =NVIC_PENDSV_PRI
	STRB R1, [R0]
	MOV R0, #0
	MSR PSP, R0
	LDR R0, __OS_Running
	MOV R1, #1
	STRB R1, [R0]
	LDR R0, =NVIC_INT_CTRL
	LDR R1, =NVIC_PENDSVSET
	STR R1, [R0]
	CPSIE I